using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KeyTones
{
	internal class KeyConst
	{
		public static readonly int VK_LBUTTON = 0x01; //Left mouse button
		public static readonly int VK_RBUTTON = 0x02; //Right mouse button
		public static readonly int VK_CANCEL = 0x03; //Control-break processing
		public static readonly int VK_MBUTTON = 0x04; //Middle mouse button
		public static readonly int VK_XBUTTON1 = 0x05; //X1 mouse button
		public static readonly int VK_XBUTTON2 = 0x06; //X2 mouse button
		public static readonly int VK_BACK = 0x08; //BACKSPACE key
		public static readonly int VK_TAB = 0x09; //TAB key
		public static readonly int VK_CLEAR = 0x0C; //CLEAR key
		public static readonly int VK_RETURN = 0x0D; //ENTER key
		public static readonly int VK_SHIFT = 0x10; //SHIFT key
		public static readonly int VK_CONTROL = 0x11; //CTRL key
		public static readonly int VK_MENU = 0x12; //ALT key
		public static readonly int VK_PAUSE = 0x13; //PAUSE key
		public static readonly int VK_CAPITAL = 0x14; //CAPS LOCK key
		public static readonly int VK_KANA = 0x15; //IME Kana mode
		public static readonly int VK_HANGUL = 0x15; //IME Hangul mode
		public static readonly int VK_IME_ON = 0x16; //IME On
		public static readonly int VK_JUNJA = 0x17; //IME Junja mode
		public static readonly int VK_FINAL = 0x18; //IME final mode
		public static readonly int VK_HANJA = 0x19; //IME Hanja mode
		public static readonly int VK_KANJI = 0x19; //IME Kanji mode
		public static readonly int VK_IME_OFF = 0x1A; //IME Off
		public static readonly int VK_ESCAPE = 0x1B; //ESC key
		public static readonly int VK_CONVERT = 0x1C; //IME convert
		public static readonly int VK_NONCONVERT = 0x1D; //IME nonconvert
		public static readonly int VK_ACCEPT = 0x1E; //IME accept
		public static readonly int VK_MODECHANGE = 0x1F; //IME mode change request
		public static readonly int VK_SPACE = 0x20; //SPACEBAR
		public static readonly int VK_PRIOR = 0x21; //PAGE UP key
		public static readonly int VK_NEXT = 0x22; //PAGE DOWN key
		public static readonly int VK_END = 0x23; //END key
		public static readonly int VK_HOME = 0x24; //HOME key
		public static readonly int VK_LEFT = 0x25; //LEFT ARROW key
		public static readonly int VK_UP = 0x26; //UP ARROW key
		public static readonly int VK_RIGHT = 0x27; //RIGHT ARROW key
		public static readonly int VK_DOWN = 0x28; //DOWN ARROW key
		public static readonly int VK_SELECT = 0x29; //SELECT key
		public static readonly int VK_PRINT = 0x2A; //PRINT key
		public static readonly int VK_EXECUTE = 0x2B; //EXECUTE key
		public static readonly int VK_SNAPSHOT = 0x2C; //PRINT SCREEN key
		public static readonly int VK_INSERT = 0x2D; //INS key
		public static readonly int VK_DELETE = 0x2E; //DEL key
		public static readonly int VK_HELP = 0x2F; //HELP key
		public static readonly int VK_ZERO = 0x30; //key
		public static readonly int VK_ONE = 0x31; //1 key
		public static readonly int VK_TWO = 0x32; //2 key
		public static readonly int VK_THREE = 0x33; //3 key
		public static readonly int VK_FOUR = 0x34; //4 key
		public static readonly int VK_FIVE = 0x35; //5 key
		public static readonly int VK_SIX = 0x36; //6 key
		public static readonly int VK_SEVEN = 0x37; //7 key
		public static readonly int VK_EIGHT = 0x38; //8 key
		public static readonly int VK_NINE = 0x39; //9 key
		public static readonly int VK_A = 0x41; //A key
		public static readonly int VK_B = 0x42; //B key
		public static readonly int VK_C = 0x43; //C key
		public static readonly int VK_D = 0x44; //D key
		public static readonly int VK_E = 0x45; //E key
		public static readonly int VK_F = 0x46; //F key
		public static readonly int VK_G = 0x47; //G key
		public static readonly int VK_H = 0x48; //H key
		public static readonly int VK_I = 0x49; //I key
		public static readonly int VK_J = 0x4A; //J key
		public static readonly int VK_K = 0x4B; //K key
		public static readonly int VK_L = 0x4C; //L key
		public static readonly int VK_M = 0x4D; //M key
		public static readonly int VK_N = 0x4E; //N key
		public static readonly int VK_O = 0x4F; //O key
		public static readonly int VK_P = 0x50; //P key
		public static readonly int VK_Q = 0x51; //Q key
		public static readonly int VK_R = 0x52; //R key
		public static readonly int VK_S = 0x53; //S key
		public static readonly int VK_T = 0x54; //T key
		public static readonly int VK_U = 0x55; //U key
		public static readonly int VK_V = 0x56; //V key
		public static readonly int VK_W = 0x57; //W key
		public static readonly int VK_X = 0x58; //X key
		public static readonly int VK_Y = 0x59; //Y key
		public static readonly int VK_Z = 0x5A; //Z key
		public static readonly int VK_LWIN = 0x5B; //Left Windows key
		public static readonly int VK_RWIN = 0x5C; //Right Windows key
		public static readonly int VK_APPS = 0x5D; //Applications key
		public static readonly int VK_SLEEP = 0x5F; //Computer Sleep key
		public static readonly int VK_NUMPAD0 = 0x60; //Numeric keypad 0 key
		public static readonly int VK_NUMPAD1 = 0x61; //Numeric keypad 1 key
		public static readonly int VK_NUMPAD2 = 0x62; //Numeric keypad 2 key
		public static readonly int VK_NUMPAD3 = 0x63; //Numeric keypad 3 key
		public static readonly int VK_NUMPAD4 = 0x64; //Numeric keypad 4 key
		public static readonly int VK_NUMPAD5 = 0x65; //Numeric keypad 5 key
		public static readonly int VK_NUMPAD6 = 0x66; //Numeric keypad 6 key
		public static readonly int VK_NUMPAD7 = 0x67; //Numeric keypad 7 key
		public static readonly int VK_NUMPAD8 = 0x68; //Numeric keypad 8 key
		public static readonly int VK_NUMPAD9 = 0x69; //Numeric keypad 9 key
		public static readonly int VK_MULTIPLY = 0x6A; //Multiply key
		public static readonly int VK_ADD = 0x6B; //Add key
		public static readonly int VK_SEPARATOR = 0x6C; //Separator key
		public static readonly int VK_SUBTRACT = 0x6D; //Subtract key
		public static readonly int VK_DECIMAL = 0x6E; //Decimal key
		public static readonly int VK_DIVIDE = 0x6F; //Divide key
		public static readonly int VK_F1 = 0x70; //F1 key
		public static readonly int VK_F2 = 0x71; //F2 key
		public static readonly int VK_F3 = 0x72; //F3 key
		public static readonly int VK_F4 = 0x73; //F4 key
		public static readonly int VK_F5 = 0x74; //F5 key
		public static readonly int VK_F6 = 0x75; //F6 key
		public static readonly int VK_F7 = 0x76; //F7 key
		public static readonly int VK_F8 = 0x77; //F8 key
		public static readonly int VK_F9 = 0x78; //F9 key
		public static readonly int VK_F10 = 0x79; //F10 key
		public static readonly int VK_F11 = 0x7A; //F11 key
		public static readonly int VK_F12 = 0x7B; //F12 key
		public static readonly int VK_F13 = 0x7C; //F13 key
		public static readonly int VK_F14 = 0x7D; //F14 key
		public static readonly int VK_F15 = 0x7E; //F15 key
		public static readonly int VK_F16 = 0x7F; //F16 key
		public static readonly int VK_F17 = 0x80; //F17 key
		public static readonly int VK_F18 = 0x81; //F18 key
		public static readonly int VK_F19 = 0x82; //F19 key
		public static readonly int VK_F20 = 0x83; //F20 key
		public static readonly int VK_F21 = 0x84; //F21 key
		public static readonly int VK_F22 = 0x85; //F22 key
		public static readonly int VK_F23 = 0x86; //F23 key
		public static readonly int VK_F24 = 0x87; //F24 key
		public static readonly int VK_NUMLOCK = 0x90; //NUM LOCK key
		public static readonly int VK_SCROLL = 0x91; //SCROLL LOCK key
		public static readonly int VK_LSHIFT = 0xA0; //Left SHIFT key
		public static readonly int VK_RSHIFT = 0xA1; //Right SHIFT key
		public static readonly int VK_LCONTROL = 0xA2; //Left CONTROL key
		public static readonly int VK_RCONTROL = 0xA3; //Right CONTROL key
		public static readonly int VK_LMENU = 0xA4; //Left ALT key
		public static readonly int VK_RMENU = 0xA5; //Right ALT key
		public static readonly int VK_BROWSER_BACK = 0xA6; //Browser Back key
		public static readonly int VK_BROWSER_FORWARD = 0xA7; //Browser Forward key
		public static readonly int VK_BROWSER_REFRESH = 0xA8; //Browser Refresh key
		public static readonly int VK_BROWSER_STOP = 0xA9; //Browser Stop key
		public static readonly int VK_BROWSER_SEARCH = 0xAA; //Browser Search key
		public static readonly int VK_BROWSER_FAVORITES = 0xAB; //Browser Favorites key
		public static readonly int VK_BROWSER_HOME = 0xAC; //Browser Start and Home key
		public static readonly int VK_VOLUME_MUTE = 0xAD; //Volume Mute key
		public static readonly int VK_VOLUME_DOWN = 0xAE; //Volume Down key
		public static readonly int VK_VOLUME_UP = 0xAF; //Volume Up key
		public static readonly int VK_MEDIA_NEXT_TRACK = 0xB0; //Next Track key
		public static readonly int VK_MEDIA_PREV_TRACK = 0xB1; //Previous Track key
		public static readonly int VK_MEDIA_STOP = 0xB2; //Stop Media key
		public static readonly int VK_MEDIA_PLAY_PAUSE = 0xB3; //Play/Pause Media key
		public static readonly int VK_LAUNCH_MAIL = 0xB4; //Start Mail key
		public static readonly int VK_LAUNCH_MEDIA_SELECT = 0xB5; //Select Media key
		public static readonly int VK_LAUNCH_APP1 = 0xB6; //Start Application 1 key
		public static readonly int VK_LAUNCH_APP2 = 0xB7; //Start Application 2 key
		public static readonly int VK_OEM_1 = 0xBA; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ;: key
		public static readonly int VK_OEM_PLUS = 0xBB; //For any country/region, the + key
		public static readonly int VK_OEM_COMMA = 0xBC; //For any country/region, the , key
		public static readonly int VK_OEM_MINUS = 0xBD; //For any country/region, the - key
		public static readonly int VK_OEM_PERIOD = 0xBE; //For any country/region, the . key
		public static readonly int VK_OEM_2 = 0xBF; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the /? key
		public static readonly int VK_OEM_3 = 0xC0; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the `~ key
		public static readonly int VK_OEM_4 = 0xDB; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the [{ key
		public static readonly int VK_OEM_5 = 0xDC; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the \\| key
		public static readonly int VK_OEM_6 = 0xDD; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ]} key
		public static readonly int VK_OEM_7 = 0xDE; //Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '" key
		public static readonly int VK_OEM_8 = 0xDF; //Used for miscellaneous characters; it can vary by keyboard.
		public static readonly int VK_OEM_102 = 0xE2; //The <> keys on the US standard keyboard, or the \\| key on the non-US 102-key keyboard
		public static readonly int VK_PROCESSKEY = 0xE5; //IME PROCESS key
		public static readonly int VK_PACKET = 0xE7; //Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit private static readonly int; Virtual = Key //value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, private static readonly int WM_KEYDOW; = , //and WM_KEYUP
		public static readonly int VK_ATTN = 0xF6; //Attn key
		public static readonly int VK_CRSEL = 0xF7; //CrSel key
		public static readonly int VK_EXSEL = 0xF8; //ExSel key
		public static readonly int VK_EREOF = 0xF9; //Erase EOF key
		public static readonly int VK_PLAY = 0xFA; //Play key
		public static readonly int VK_ZOOM = 0xFB; //Zoom key
		public static readonly int VK_PA1 = 0xFD; //PA1 key
		public static readonly int VK_OEM_CLEAR = 0xFE; //Clear key
	}
}
